version: '3.4'

services:
  sauce:
    image: sauce-img
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGO_URI: 'mongodb://sauce-mongodb:27017/sauce?retryWrites=true&w=majority'
      MAILMAN_URL: 'http://lists.sccs.swarthmore.edu:8001/3.1'
      PORT: 7567
    ports:
      - 7567:7567
    restart: always
    volumes:
      - ./_posts:/sauce-app/_posts
      - ./_docs:/sauce-app/_docs
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - 'mongodb'
    networks:
      - internal
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:7567']
      interval: 30s
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo:5.0.29
    restart: always
    hostname: sauce-mongodb
    volumes:
      - './mongodata:/data/db'
    networks:
      - internal

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - discord-agent/.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - internal

  sauce_bot:
    #image: registry.sccs.swarthmore.edu/sccs/saunce_bot/sauce_bot:latest
    image: sauce_bot
    build:
      context: discord-agent
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - discord-agent/.env
    networks:
      - internal

volumes:
  rabbitmq_data:

networks:
  internal:
