version: '3.4'

services:
  sauce:
    image: sauce-img
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGO_URI: "mongodb://sauce-mongodb:27017/sauce?retryWrites=true&w=majority"
      MAILMAN_URL: "http://lists.sccs.swarthmore.edu:8001/3.1"
      PORT: 7567
    restart: always
    volumes:
      - ./_posts:/sauce-app/_posts
      - ./_docs:/sauce-app/_docs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "mongodb"

  mongodb:
    image: mongo:5.0.5
    restart: always
    hostname: sauce-mongodb
    volumes:
      - './mongodata:/data/db'
